version: "3.9"
services:
  postgres:
      image: postgres
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/"]
      interval: 30s
      timeout: 10s
      retries: 15
    ports:
      - 8280:8080
    depends_on:
      - postgres

      
  server:
    build: ./spring-server
    ports:
      - "8082:8082"
    depends_on:
      keycloak:
        condition: service_healthy

  client:
    image: vaadin-docker
    ports:
      - "80:80"
    depends_on:
      keycloak:
        condition: service_healthy

volumes:
  postgres-data:
    driver: local
