//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.12 at 02:31:33 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.unimi.it/distanceinair/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.unimi.distanceinair.client.domain.xml;
