//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.03 at 10:04:45 PM CEST 
//


package it.unimi.distanceinair.server.xml.domain;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="flights" type="{http://www.unimi.it/distanceinair/}DistanceInAir" maxOccurs="10"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "flights"
})
@XmlRootElement(name = "GetPossibleFlightsResponse")
public class GetPossibleFlightsResponse {

    @XmlElement(required = true)
    protected List<DistanceInAir> flights;

    /**
     * Gets the value of the flights property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flights property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlights().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DistanceInAir }
     */
    public List<DistanceInAir> getFlights() {
        if (flights == null) {
            flights = new ArrayList<DistanceInAir>();
        }
        return this.flights;
    }

    /**
     * Sets the value of the flights property.
     *
     * @param flights allowed object is
     *                {@link DistanceInAir }
     */
    public void setFlights(List<DistanceInAir> flights) {
        this.flights = flights;
    }

}
