vaadin:
  launch-browser: 'true'
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application

soap:
  client_pwd: u9u6GT&j!10^
  server_pwd: ART*18HKUhC1
  soapActive: 'true'
  server_keystore: classpath:server-keystore.jks
  client_keystore: classpath:client-keystore.jks
  server_alias: progetto-unimi
  client_alias: studente-giovanni
  api-url: http://server:8082/
spring:
  mustache:
    check-template-location: 'false'
  jpa:
    defer-datasource-initialization: 'true'
  security:
    oauth2:
      client:
        registration:
          keycloak:
            scope: openid
            authorization-grant-type: authorization_code
            client-id: soasec-client
        provider:
          keycloak:
            issuer-uri: http://kubernetes.docker.internal:8280/auth/realms/soasec-project
            user-name-attribute: preferred_username

logging:
  level:
    org:
      atmosphere: info
server:
  servlet:
    session:
      timeout: 59m
  port: ${PORT:80}
